### PR TITLE
Add specs for TechTag/Page models, Welcome/Notification mailers

### PR DESCRIPTION
**Pull request by reprah**
I wrote specs for the two mailers and two of the models. Again, let me know if I need to change something before you consider merging. Thanks!

### CODE REVIEW

**Comment by damian-sowers** [comment]
Perfect, thanks! Sorry it took me a day to merge it. I didn't see the pull request initially.

**Comment by reprah** [comment]
One day isn't much of a delay!

Are you still brainstorming features with the other people who forked mycelial?

**Comment by damian-sowers** [comment]
Yeah. Another guy is going to write a markdown powered blog for it. I'm still planning on adding some features as well. Just been a little busy lately :)

**Comment by reprah** [comment]
Let me know if you're open to more contributions, like maybe small changes that would make it easier to upgrade to Rails 4 later on. I want to help, but don't have a clear idea about the level of participation you want from outsiders or where you want Mycelial to go. Open offer :-) You can pull my email from Git's logs.

**Pull request merged**
